

const REGISTER_REQUEST = "REGISTER_REQUEST"
const REGISTER_ERROR = "REGISTER_ERROR"
const REGISTER_SUCCESS = "REGISTER_SUCCESS"

const AUTH_REQUEST = "AUTH_REQUEST"
const AUTH_ERROR = "AUTH_ERROR"
const AUTH_SUCCESS = "AUTH_SUCCESS"

